---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: birds-app-back-end-deployment
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: birds-app-back-end-showalter
  template:
    metadata:
      labels:
        app: birds-app-back-end-showalter
    spec:
      containers:
        - image: 'ghcr.io/showalter/birds-app-back-end:00c2924bd49a1cc5ef2fb81508b26d488cbda792'
          name: birds-back-front-end
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
