---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: birds-app-back-end-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: birds-app-back-end-showalter
  template:
    metadata:
      labels:
        app: birds-app-back-end-showalter
    spec:
      containers:
        - image: 'ghcr.io/showalter/birds-app-back-end:1b859a5f50b3856df5ff76df74e22206ee987670'
          name: birds-back-front-end
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
